### PR TITLE
New roslaunch and rosstart commands

### LINKED ISSUE #18: [feature] ros{start,exec,...}
You got a new user now (at least for some setups). Nice work to everyone involved. :smile: 
Here's an unabashed feature request. :dog2: 

The main feature I always thought any such convenience layer should have is a command merging `rosrun/ros2 run` and `roslaunch/ros2 launch` with tab completion. What do you think about that @DLu ?

### PR DESCRIPTION
**Pull request by DLu**
Closes #18 

 * ~Enhances all `argparse.ArgumentParser`s with [`argcomplete`](https://github.com/kislyuk/argcomplete)~ In #23
 * ~Reimplements `list_interfaces` to avoid calling `async` function within arg completion.~ In #23 
 * Adds new wrapper for `roslaunch`
 * Adds new command `rosstart` which combines `rosrun` and `roslaunch`

### CODE REVIEW

**Comment by DLu** [comment]
@v4hn give this a try and let me know if it works the way you want.

**Comment by v4hn** [comment]
I played around with the branch for a bit and fixed some issues in my fork:
https://github.com/v4hn/ros_command/tree/argcomplete
I only touched the ROS1 parts of the code as I can't test the ROS2 interfaces right now.
Some notes:

- `rosstart` collides with `rosservice` and `rosstack` with bad usability via tab completion. So I renamed it to `rosexecute` which only collides with `rosed`
- I'm unhappy with `argcomplete` because it takes significantly longer to tab-complete. original takes <100ms over here, but the `ros_command` versions take ~500ms. I'm not convinced this is worth the much cleaner code.
- `roslaunch <pkg> <file> <tab>` traditionally autocompletes names of the args defined in the launch file. This is really useful and `ros_command` doesn't do it yet.

**Comment by v4hn** [comment]
I forgot one other major issue on my system:

- When I execute/launch launch files that only produce little command line output with your wrappers, I do not see any output on the command line at all. I expect some unexpected buffering goes on in [your stdout wrapping mechanism](https://github.com/MetroRobots/ros_command/blob/9efe986ea9912ae94ad300a38b2e664c67ad0268/ros_command/command_lib.py#L19-L21). I'm not sure whether arbitrary nodes via rosrun are affected too, I didn't investigate further.

**Comment by v4hn** [comment]
Here's another major blocker on ROS in devel workspaces: scripts from the source package do not auto-complete with  `rosexecute` nor with `rosrun`. `rosrun` can still run them, but `rosexecute` will decide to call roslaunch which fails with
> RLException: Invalid roslaunch XML syntax: not well-formed (invalid token): line 1, column 1

**Comment by DLu** [comment]
> * `roslaunch <pkg> <file> <tab>` traditionally autocompletes names of the args defined in the launch file. This is really useful and `ros_command` doesn't do it yet.

Now it does.

**Comment by v4hn** [comment]
ping.
I know there are some things left to do here.
But `rosexecute` would still be nice. :-)

**Pull request merged**
